# Base de datos
db.url=jdbc:mysql://192.168.1.183:3306/levelup_arcade?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
db.user=root
db.password=campusfp

# Logs
log.path=logs/app.log

# App
app.name=LevelUp Arcade

# OpenRouter - Fase 5
openrouter.api.key=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
openrouter.model=openrouter/free
openrouter.url=https://openrouter.ai/api/v1/chat/completions
openrouter.referer=http://localhost
openrouter.appname=LevelUpArcade
